# Generated by Django 5.2.4 on 2025-07-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
