# Generated by Django 5.2.4 on 2025-07-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantiy',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('m', '32'), ('l', '47'), ('xl', '52')], default='32', max_length=4),
        ),
    ]
