# Generated by Django 5.2.3 on 2025-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='m.jpg', upload_to='profile_path'),
        ),
    ]
